#!/bin/sh

set -e

IMAGE_NAME="registry-bosa-city.bosa.belighted.com/bosa-city"
TAG=${TAG:-"latest"}

runpath="$( cd "$(dirname "$0")" ; pwd -P )"
#(cd ${runpath} &&
#     docker build --file ${runpath}/Dockerfile --pull --tag $IMAGE_NAME:$TAG ../../.. &&
#     docker push $IMAGE_NAME:$TAG)

(cd ${runpath} &&
     docker build --file ${runpath}/Dockerfile --pull --tag $IMAGE_NAME:$TAG ../../.. )
