#!/bin/sh

set -e

IMAGE_NAME="base.bosa-cities.belighted.com/bosa-cities-base"
TAG=${TAG:-"latest"}

runpath="$( cd "$(dirname "$0")" ; pwd -P )"
(cd ${runpath} &&
     docker build --file ${runpath}/Dockerfile --pull --tag $IMAGE_NAME:$TAG ../..)
