#!/bin/sh

set -e

IMAGE_NAME="registry-bosa-city-base.bosa.belighted.com/bosa-city-base"
TAG=${TAG:-"latest"}

runpath="$( cd "$(dirname "$0")" ; pwd -P )"
(cd ${runpath} &&
     docker build --file ${runpath}/Dockerfile --pull --tag $IMAGE_NAME:$TAG ../.. &&
     docker push $IMAGE_NAME:$TAG)
