# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  admin_sign_in_path: "admin_sign_in"
  omniauth:
    facebook:
      # It must be a boolean. Remember ENV variables doesn't support booleans.
      enabled: false
      app_id: <%= ENV["OMNIAUTH_FACEBOOK_APP_ID"] %>
      app_secret: <%= ENV["OMNIAUTH_FACEBOOK_APP_SECRET"] %>
    twitter:
      enabled: false
      api_key: <%= ENV["OMNIAUTH_TWITTER_API_KEY"] %>
      api_secret: <%= ENV["OMNIAUTH_TWITTER_API_SECRET"] %>
    google_oauth2:
      enabled: false
      client_id: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] %>
      client_secret: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_SECRET"] %>
#    decidim:
#      enabled: true
#      icon_path: "decidim/decidim-logo-mobile--inv.svg"
#      provider_name: "Decidim SSO"
#      client_id: <%= ENV["OMNIAUTH_DECIDIM_CLIENT_ID"] %>
#      client_secret: <%= ENV["OMNIAUTH_DECIDIM_CLIENT_SECRET"] %>
#      site_url: <%= ENV["OMNIAUTH_DECIDIM_SITE_URL"] %>
    saml:
      enabled:                        true
      provider_name:                  "SAML-STAGING"
      icon_path:                      "eid-logo.svg"
      idp_sso_target_url:             <%= ENV["OMNIAUTH_SAML_SSO_URL"] %>
      assertion_consumer_service_url: <%= ENV["OMNIAUTH_SAML_CALLBACK"] %>
      authn_context:                  <%= ENV["OMNIAUTH_SAML_AUTHN_CONTEXT"] %>
      issuer:                         <%= ENV["OMNIAUTH_SAML_ISSUER"] %>
      idp_slo_target_url:             <%= ENV["OMNIAUTH_SAML_SLO_URL"] %>
      idp_cert_fingerprint:          <%= ENV["OMNIAUTH_SAML_CERT_FINGERPRINT"] %>
      idp_cert:                       <%= ENV["OMNIAUTH_SAML_CERT"] %>
      idp_key:                        <%= ENV["OMNIAUTH_SAML_KEY"] %>
      person_services_wsdl:           <%= ENV["PERSON_SERVICES_WSDL"] %>
      person_services_cert:           <%= ENV["PERSON_SERVICES_CERT"] %>
      person_services_ca_cert:        <%= ENV["PERSON_SERVICES_CA_CERT"] %>
      person_services_key:            <%= ENV["PERSON_SERVICES_KEY"] %>
      person_services_secret:         <%= ENV["PERSON_SERVICES_SECRET"] %>
      person_services_proxy:          <%= ENV["PERSON_SERVICES_PROXY"] %>
      person_services_fallback_rrn:    <%= ENV["PERSON_SERVICES_FALLBACK_RRN"] %>

    csam:
      enabled:                        true
      provider_name:                  <%= ENV["OMNIAUTH_CSAM_PROVIDER_NAME"] %>
      icon_path:                      "eid-logo.svg"
      idp_sso_target_url:             <%= ENV["OMNIAUTH_CSAM_IDP_SSO_TARGET_URL"] %>
      idp_slo_target_url:             <%= ENV["OMNIAUTH_CSAM_IDP_SLO_TARGET_URL"] %>
      assertion_consumer_service_url: <%= ENV["OMNIAUTH_CSAM_ASSERTION_CONSUMER_SERVICE_URL"] %>
      authn_context:                  <%= ENV["OMNIAUTH_CSAM_AUTHN_CONTEXT"] %>
      issuer:                         <%= ENV["OMNIAUTH_CSAM_ISSUER"] %>
      idp_cert: ""
      idp_key: ""
      person_services_wsdl:           <%= ENV["PERSON_SERVICES_WSDL"] %>
      person_services_cert:           <%= ENV["PERSON_SERVICES_CERT"] %>
      person_services_ca_cert:        <%= ENV["PERSON_SERVICES_CA_CERT"] %>
      person_services_key:            <%= ENV["PERSON_SERVICES_KEY"] %>
      person_services_secret:         <%= ENV["PERSON_SERVICES_SECRET"] %>
      person_services_proxy:          <%= ENV["PERSON_SERVICES_PROXY"] %>
      person_services_fallback_rrn:    <%= ENV["PERSON_SERVICES_FALLBACK_RRN"] %>

  geocoder:
    here_api_key: <%= ENV["GEOCODER_LOOKUP_API_KEY"] %>
  etherpad:
    server: <%= ENV["ETHERPAD_SERVER"] %>
    api_key: <%= ENV["ETHERPAD_API_KEY"] %>
    api_version: "1.2.1"
  carrierwave:
    enabled: <%= ENV["CARRIERWAVE_ENABLED"] %>
    provider: <%= ENV["CARRIERWAVE_PROVIDER"] %>
    aws_access_key_id: <%= ENV["CARRIERWAVE_AWS_ACCESS_KEY"] %>
    aws_secret_access_key: <%= ENV["CARRIERWAVE_AWS_SECRET_ACCESS_KEY"] %>
    region: <%= ENV["CARRIERWAVE_REGION"] %>
    host: <%= ENV["CARRIERWAVE_HOST"] %>
    endpoint: <%= ENV["CARRIERWAVE_ENDPOINT"] %>
    path_style: <%= ENV["CARRIERWAVE_PATH_STYLE"] %>
    fog_directory: <%= ENV["CARRIERWAVE_FOG_DIRECTORY"] %>
    asset_host: <%= ENV["CARRIERWAVE_ASSET_HOST"] %>

development:
  <<: *default
  secret_key_base: f29d4cdbacaff2279b8580b025878a9e591846de1e9907691165f86e85384d73b4885e6f96719b61fd49a60d2bf12b4342e0e2bd2be407cee2f39356d71019de

test:
  <<: *default
  secret_key_base: a3a8d9cb9ca3e682e2552e8d0c5ad88069339c136338174c5c76ef3970249df6cd18f3220e527b1956d01d9871f89064bad5955e5d8e40e2a39c4e4f5c11eee0
  omniauth:
    facebook:
      enabled: true
    twitter:
      enabled: true
    google_oauth2:
      enabled: true

staging:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  admin_sign_in_path: <%= ENV["DECIDIM_ADMIN_SIGN_IN_PATH"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_domain: <%= ENV.fetch( "SMTP_DOMAIN", 'smtp.mailtrap.io') %>
  smtp_port: <%= ENV.fetch("SMTP_PORT", 587) %>
  smtp_starttls_auto: true
  smtp_authentication: <%= ENV.fetch("SMTP_AUTH", 'cram_md5') %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  admin_sign_in_path: <%= ENV["DECIDIM_ADMIN_SIGN_IN_PATH"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  smtp_starttls_auto: true
  smtp_authentication: <%= ENV["SMTP_AUTH"] %>
