:concurrency: 6
:queues:
  - default
  - mailers
  - newsletter
  - newsletters_opt_in
  - events
  - metrics

:schedule:
  CalculateAllMetrics:
    cron: '0 14 * * *'
    class: CalculateAllMetricsJob
  PreloadOpenData:
    cron: '0 17 * * *'
    class: PreloadOpenDataJob
#  CheckPublishedInitiatives:
#    cron: '0 16 * * *'
#    class: CheckPublishedInitiatives
#  CheckValidatingInitiatives:
#    cron: '30 16 * * *'
#    class: CheckValidatingInitiatives
#  NotifyProgressInitiatives:
#    cron: '45 8,16,23 * * *'
#    class: NotifyProgressInitiatives
  CleanSessions:
    cron: '0 5 * * *'
    class: CleanSessions
